// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qclktzhkhgtcspocqqhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbGt0emhraGd0Y3Nwb2NxcWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDkzMTEsImV4cCI6MjA2ODU4NTMxMX0.ytN8nRo0cNJiUgvX2Ky4gEgMUD_YQiMyQc88Ze4KcOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});